baseURL: 'https://keks.dev/'
languageCode: en-us
title: keks.dev
theme: PaperMod
minify:
  disableXML: true
  minifyOutput: true
menu:
  main:
    - identifier: publications
      name: publications
      url: /publications/
      weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 20
params:
  hideFooter: true
  defaultTheme: auto
  ShowCodeCopyButtons: true
  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    subtitle: "Hi, I'm Christoph"
    imageUrl: "me.jpg" # optional
    imageTitle: "" # optional
    imageWidth: 196 # custom size
    imageHeight: 196 # custom size


  socialIcons: # optional
      - name: "github"
        url: "https://github.com/Schroedi"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/christoph-schr%C3%B6der-48520081/"
